import axios from "axios";

export const api = axios.create({
  baseURL: "/api/bff",
  timeout: 10000,
  headers: {
    Accept: "application/json",
  },
  withCredentials: true,
});

export const constraintMessages = new Map<string, string>([
  ["isDefined", "This field is required"],
  ["isOptional", "This field is optional"],
  ["isString", "Must be a string"],
  ["isNotEmpty", "Must not be empty"],
  ["isEmpty", "Must be empty"],
  ["length", "Must match the length"],
  ["minLength", "Must match the minimum length"],
  ["maxLength", "Must match the maximum length"],
  ["matches", "Must match the required pattern"],
  ["isNumber", "Must be a number"],
  ["isInt", "Must be an integer"],
  ["isPositive", "Must be a positive number"],
  ["isNegative", "Must be a negative number"],
  ["min", "Must match the minimum value"],
  ["max", "Must match the maximum value"],
  ["isDate", "Must be a valid date"],
  ["minDate", "Date must not be before the minimum date"],
  ["maxDate", "Date must not be after the maximum date"],
  ["isBoolean", "Must be a boolean value"],
  ["isArray", "Must be an array"],
  ["arrayMinSize", "Array must contain the required number of elements"],
  [
    "arrayMaxSize",
    "Array must contain no more than the maximum number of elements",
  ],
  ["arrayNotEmpty", "Array must not be empty"],
  ["isEnum", "Must be a valid enum value"],
  ["isObject", "Must be an object"],
  ["isEmail", "Must be a valid email address"],
  ["isURL", "Must be a valid URL"],
  ["isFQDN", "Must be a valid fully qualified domain name"],
  ["isIP", "Must be a valid IP address"],
  ["isUUID", "Must be a valid UUID"],
  ["isMongoId", "Must be a valid MongoDB ObjectId"],
  ["isLatitude", "Latitude must be between -90 and 90"],
  ["isLongitude", "Longitude must be between -180 and 180"],
  ["isCreditCard", "Must be a valid credit card number"],
  ["isHexColor", "Must be a valid hex color"],
  ["isLowercase", "Must be lowercase"],
  ["isUppercase", "Must be uppercase"],
  ["isAlpha", "Must contain only letters"],
  ["isAlphanumeric", "Must contain only letters and numbers"],
  ["isDecimal", "Must be a decimal number"],
  ["isJSON", "Must be a valid JSON string"],
]);
